export const API_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  TOO_MANY_URLS: 'TOO_MANY_URLS',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  JOB_ALREADY_FINISHED: 'JOB_ALREADY_FINISHED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
